spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scooter
    username: myuser
    password: password
    initialization-mode: always
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
